version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/logs:/var/log/nginx/log
    depends_on:
      - openhab
      - mosquitto
    ports:
      - 80:80
      - 443:443
      - 1884:1884
    networks:
      - iot-network
      - admin
  
  openhab:
    image: openhab/openhab:2.5.4
    container_name: openhab
    user: openhab
    volumes:
      - ./openhab/addons:/openhab/addons
      - ./openhab/conf:/openhab/conf
      - ./openhab/userdata:/openhab/userdata
    depends_on:
      - mosquitto
    networks:
      - iot-network
    environment:
      - EXTRA_JAVA_OPTS=-Xms16m -Xmx256m -Xbootclasspath/a:/openhab/conf/libs/jython/jython-2.7.2.jar -Dpython.home=/openhab/conf/libs/jython -Dpython.path=/openhab/conf/libs/python
    expose:
      - "8080"
      - "8443"
    dns: "192.168.1.1"

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    user: mosquitto
    volumes:
      - ./mosquitto/conf:/mosquitto/conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    expose:
      - "1883"
      - "9001"
    networks:
      - iot-network
  
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    expose:
      - "9000"
      - "8000"
    networks:
      - admin

networks:
  iot-network:
    name: iot-network
    driver: bridge
  admin:
    name: admin
    driver: bridge

