homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee
  server: 'mqtt://mosquitto:1883'
  client_id: zigbee
  user: '!secret user'
  password: '!secret password'
  version: 5
serial:
  port: /dev/ttyUSB0
advanced:
  log_directory: data/log
  log_file: zigbee2mqtt_%TIMESTAMP%.log
  log_output:
    - file
    - console
  network_key: '!secret network_key'
  availability_timeout: 900
  channel: 11
  rtscts: false
devices: devices.yaml
