homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee
  server: 'mqtt://mosquitto:1883'
  user: '!secret user'
  password: '!secret password'
  client_id: zigbee
serial:
  port: /dev/ttyUSB0
advanced:
  log_directory: data/log
  log_file: zigbee2mqtt_%TIMESTAMP%.log
  log_output:
    - file
  network_key: '!secret network_key'
devices: devices.yaml
